# Generated by Django 4.2.4 on 2023-08-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='employee_rating',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='completed_tasks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
