# Generated by Django 4.2.4 on 2023-09-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_delivery_generated_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(choices=[('Pracownik', 'Pracownik'), ('Szef', 'Szef'), ('Admin', 'Admin')], default='Pracownik', max_length=10),
        ),
    ]
