# Generated by Django 4.2.4 on 2023-09-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_alter_userprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('Do spakowania', 'Do spakowania'), ('Przygotowany', 'Przygotowany'), ('Odebrany', 'Odebrany')], default='Do spakowania', max_length=20),
        ),
    ]
