# Generated by Django 4.2.4 on 2023-09-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_alter_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='notice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='package_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='return',
            name='receiving_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='wholesale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
