# Generated by Django 4.2.4 on 2023-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_return_notes_return_notice_return_package_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='return',
            name='notice',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='return',
            name='receiving_company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='return',
            name='wholesale',
            field=models.CharField(max_length=50),
        ),
    ]
