# Generated by Django 4.2.4 on 2023-09-16 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_rename_product_list_return_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Do zamówienia', 'Do zamówienia'), ('Zamówiony', 'Zamówiony'), ('Niedostępny', 'Niedostępny')], default='Do zamówienia', max_length=20)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
