# Generated by Django 4.2.4 on 2023-09-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0008_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Do zamówienia', 'Do zamówienia'), ('Zamówione', 'Zamówiony'), ('Niedostępne', 'Niedostępny')], default='Do zamówienia', max_length=20),
        ),
    ]
