# Generated by Django 4.2.4 on 2023-09-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0009_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Do zamówienia', 'Do zamówienia'), ('Zamówione', 'Zamówione'), ('Niedostępne', 'Niedostępne')], default='Do zamówienia', max_length=20),
        ),
    ]
