# Generated by Django 4.2.4 on 2023-09-19 21:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0011_alter_task_status_inventoryitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItem',
            new_name='StockItem',
        ),
    ]
