# Generated by Django 4.2.4 on 2023-09-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_rename_inventoryitem_stockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='dimensions',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
