# Generated by Django 4.2.4 on 2023-09-27 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0014_orderitem_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('Zadanie', 'Zadanie'), ('Dostawa', 'Dostawa'), ('Zwrot', 'Zwrot'), ('Zamówienie', 'Zamówienie'), ('Magazyn', 'Magazyn')], max_length=150)),
                ('model_id', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Przeczytane', 'Przeczytane'), ('Nieprzeczytane', 'Nieprzeczytane')], default='Nieprzeczytane', max_length=20)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notify_for', models.CharField(choices=[('Pracownik', 'Pracownik'), ('Other', 'Other')], max_length=20)),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
