# Generated by Django 4.2.4 on 2023-09-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_remove_notification_status_notification_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='model_destiantion',
            field=models.CharField(default='', max_length=150),
        ),
    ]
