# Generated by Django 4.2.4 on 2023-09-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_notification_model_destiantion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='model_destiantion',
            field=models.CharField(max_length=150),
        ),
    ]
