# Generated by Django 4.2.4 on 2023-10-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0018_alter_notification_model_destiantion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='model_destiantion',
        ),
        migrations.AlterField(
            model_name='notification',
            name='model_name',
            field=models.CharField(choices=[('Godzina', 'Godzina'), ('Zadanie', 'Zadanie'), ('Dostawa', 'Dostawa'), ('Zwrot', 'Zwrot'), ('Zamówienie', 'Zamówienie'), ('Magazyn', 'Magazyn')], max_length=150),
        ),
    ]
