# Generated by Django 4.2.4 on 2023-10-05 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0019_remove_notification_model_destiantion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='Website.comment'),
        ),
    ]
