# Generated by Django 4.2.4 on 2023-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0020_comment_delivery_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='model_name',
            field=models.CharField(choices=[('Godzina', 'Godzina'), ('Zadanie', 'Zadanie'), ('Dostawa', 'Dostawa'), ('Zwrot', 'Zwrot'), ('Zamówienie', 'Zamówienie'), ('Magazyn', 'Magazyn'), ('Komentarz', 'Komentarz')], max_length=150),
        ),
    ]
