# Generated by Django 4.2.4 on 2023-10-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0021_alter_notification_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='comments',
            field=models.ManyToManyField(blank=True, to='Website.comment'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notify_for',
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_for',
            field=models.ManyToManyField(blank=True, to='Website.userprofile'),
        ),
    ]
