# Generated by Django 4.2.4 on 2023-10-10 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Website', '0022_alter_delivery_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_for',
            field=models.ManyToManyField(blank=True, related_name='notifications_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
