# Generated by Django 4.2.4 on 2023-10-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0023_alter_notification_notify_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_for',
            field=models.ManyToManyField(blank=True, related_name='notifications_for', to='Website.userprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_by',
            field=models.ManyToManyField(related_name='read_notifications', to='Website.userprofile'),
        ),
    ]
