# Generated by Django 4.2.4 on 2023-10-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0024_alter_notification_notify_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/invoice_pdfs/'),
        ),
    ]
