# Generated by Django 4.2.4 on 2023-10-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0025_delivery_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(blank=True, to='Website.comment'),
        ),
    ]
